### ISSUE TITLE
Does this work for Android 11

### ISSUE THREAD

**Issue by SRIKAR-B-S-S** [jaxparrow07/network-tools-rush#1]
Hi @jaxparrow07 
Does this extension work for Android 11 ?

**Comment by jaxparrow07** [comment]
Haven't tested myself. Btw, it doesn't require any advanced permission. So, I guess it will work on Android 11. Feel free to test and respond. So, I'll add in the extension thread about the android version support. Thanks for reaching out. :)

**Comment by SRIKAR-B-S-S** [comment]
**So, I'll add in the extension thread about the android version support.**
I can't get this line @jaxparrow07

**Comment by jaxparrow07** [comment]
Means I'll add something like this

**Tested on Android 11 - Working**

**Comment by SRIKAR-B-S-S** [comment]
*Tested on Android 11 - Working*
But does this actually work on Android 11?

**Comment by jaxparrow07** [comment]
Please, take a look at what I've said. Once you test and notify me. I said I'll add that in the extension thread in Kodular Community.

**Comment by SRIKAR-B-S-S** [comment]
Sorry, @jaxparrow07 I don't have an Android 11 phone
but once DM me on Kodular Community
https://community.kodular.io/u/b.s.s.srikar

**Comment by SRIKAR-B-S-S** [comment]
but once DM me on Kodular Community or Discord
https://community.kodular.io/u/b.s.s.srikar or Discord _**B.S.S.SRIKAR#4993**_
I need to talk something important with you...
